### ISSUE TITLE
[Bug] Search Loading not disappearing

### ISSUE THREAD

**Issue by Mouffassa** [stratuma/Crunchyroll-Downloader-v4.0#1]
Hello,

* Unable choose resolution (Only 1080p is available)
* Unable choose output path
* Unable download without choosing a subtitle
  Can you fix this in the next update?

Otherwise all rest works correctly
THANKS

**Comment by stratuma** [comment]
Hey, I'm gonna fix the "forced subtitle" error now.
I will implement the other suggestions in the next update!

**Comment by Mouffassa** [comment]
Many Thanks :)
Work well

![2024-04-21 21_31_36-91 92 244 228_7483](https://github.com/stratuma/Crunchyroll-Downloader-v4.0/assets/147192933/2dea69d3-42f7-475f-b6c5-aeb259f17bb5)

P.S: On Windows you have to launch the software with administrator privileges for it to work correctly.

**Comment by stratuma** [comment]
Thats strange, I'm gonna inspect it rn.

**Comment by stratuma** [comment]
Can you explain whats not working right?

**Comment by Mouffassa** [comment]
After selecting the desired anime it remains in loop
Unable to download

![2024-04-22 15_18_46-91 92 244 228_7483 - Connexion Bureau à distance](https://github.com/stratuma/Crunchyroll-Downloader-v4.0/assets/147192933/a9c92a5e-4baa-4435-b417-f4a909d1fdad)

Only on windows without admin privileges

**Comment by Mouffassa** [comment]
With admin privileges work well

![Uploading 001.png…]()

![Uploading 002.png…]()

![Uploading 003.png…]()

**Comment by Mouffassa** [comment]
With admin privileges work well

![001](https://github.com/stratuma/Crunchyroll-Downloader-v4.0/assets/147192933/48a122a2-b40c-4e7b-9205-ed320e745a80)

![Uploading 002.png…]()

![Uploading 003.png…]()

**Comment by stratuma** [comment]
Thx for the report, I fixed it and it will work in the new version.
