### ISSUE TITLE
[BUG] Mp4decrypt path invalid when space in username

### ISSUE THREAD

**Issue by AsIFall** [stratuma/Crunchyroll-Downloader-v4.0#11]
**Describe the bug**
Bei der Nutzung des Crunchyroll Downloaders habe ich feststellen müssen, dass der Download der Audio-Datei abbricht, wodurch das Video nicht gespeichert werden kann. Der Videodownload läuft weiter.
![Screenshot (237)](https://github.com/stratuma/Crunchyroll-Downloader-v4.0/assets/110290203/c4bbb49d-a136-4029-ab1d-cb4dfbb2909d)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by stratuma** [comment]
Könntest du bitte deine error.log teilen?
(Bitte sensible daten vorher rauslöschen)
Diese befindet sich unter /Dokumente/Crunchyroll Downloader/logs/error.log

**Comment by AsIFall** [comment]
{"error":{"cmd":"C:\\Users\\[GELÖSCHT]\\AppData\\Local\\Programs\\crunchyroll-downloader\\resources\\mp4decrypt\\mp4decrypt.exe --show-progress --key e3758cf490903affaf2c59955f93b2ba:96189a00e6d6cdad54b3556de2cf49c6 \"C:\\Users\\[GELÖSCHT]\\AppData\\Local\\Temp\\crd-tmp-txbmzsk356/temp-main.m4s\" \"C:\\Users\\{GELÖSCHT]\\AppData\\Local\\Temp\\crd-tmp-txbmzsk356/main.m4s\"","code":1,"killed":false,"signal":null,"stderr":"Der Befehl \"C:\\Users\\[GELÖSCHT]\\\" ist entweder falsch geschrieben oder\r\nkonnte nicht gefunden werden.\r\n","stdout":""},"level":"error","message":"Error merging video parts of Download 6","section":"crunchyrollDownloadProcessVideoMerging","service":"user-service","timestamp":"2024-06-20T07:00:19.308Z"}

So richtig?

**Comment by stratuma** [comment]
Vielen Dank, ich weiß jetzt was der Bug ist.
Der Downloader hat schwierigkeiten mp4decrypt zu starten weil dein User ein Namen mit Space hat, was ich eigentlich schon gefixt habe. Ich werde mir das nochmal genauer anschauen

**Comment by AsIFall** [comment]
Danke dir für deine Mühen.

**Comment by stratuma** [comment]
Sollte im neuen update (1.1.9) gefixt sein

**Comment by AsIFall** [comment]
> Sollte im neuen update (1.1.9) gefixt sein

Leider nicht.

**Comment by stratuma** [comment]
> Leider nicht.

https://www.swisstransfer.com/d/50893818-6c4e-4cd9-98b1-d8c7f645a093

Das ist ein weiterer testfix, kannst du ihn mal ausprobieren?

**Comment by AsIFall** [comment]
> > Leider nicht.
> 
> https://www.swisstransfer.com/d/50893818-6c4e-4cd9-98b1-d8c7f645a093
> 
> Das ist ein weiterer testfix, kannst du ihn mal ausprobieren?

Hat funktioniert! Super. Danke!
