### ISSUE TITLE
[FEATURE] Episode Name Multilanguage support (Naming)

### ISSUE THREAD

**Issue by LorenorZorro3000** [stratuma/Crunchyroll-Downloader-v4.0#15]
Servus

Kannst du vielleicht noch eine Option beim Naming hinzufügen, damit er noch die Folgen-Namen übernimmt?
Und dass er sich dann an der Dub-Sprache orientiert in welcher Sprache er die Folgen benennt.
Das wäre noch der Oberhammer.

Vielen Dank schon mal!

MFG LorenorZorro

**Comment by stratuma** [comment]
Ich werde es mir anschauen und dann in 1.2.0 einbauen

**Comment by LorenorZorro3000** [comment]
Der Hammer!

Vielen vielen Dank!

**Comment by LorenorZorro3000** [comment]
Super, er benennt die Folgen in Englisch, das funktioniert so weit. 
Danke dafür schon mal.
Gäbe es noch die Möglichkeit das er die Folgen mit den deutschen Folgennamen benennt.

Vielen Dank für deine Bemühungen und für das tolle Programm.

MFG LorenorZorro

**Comment by stratuma** [comment]
Hmm, könnte schwierig werden, da ich für jede Sprache einmal alles von Crunchyroll ziehen muss.
Ich schaugs mir aber mal an, kann aber nichts garantieren.

**Comment by LorenorZorro3000** [comment]
Alles klar, kein Stress.
Sorry hätte nicht gedacht, dass das so tricky wird.

**Comment by LorenorZorro3000** [comment]
Ich weiß ja nicht, wie du aktuell die Namen extrahierst.
Aber könnte Mann es anhand des Linkes den Mann, einfügt machen.

z.b. https://www.crunchyroll.com/de/series/GZJH3D719/tsukimichi--moonlit-fantasy-" anhand des "/de/" Damit das Programm dann weiß Deutsche-Titel.
Auf der Website selber sind die Namen dann unter <a tabindex="0" class="playable-card-hover__link--YVbhn" title="S1 E1 - Erste Nacht: Als Held … ungeeignet" href="/de/watch/G8WUN2W3W/failed-hero"></a>

Also bei "playable-card-hover__link--YVbhn"

Keine Ahnung, ob dir das hilft.

**Comment by stratuma** [comment]
So funktioniert der downloader nicht, er holt sich verschiedene versionen und jede version gibt immer nur den titel in der sprache der version zurück.

**Comment by LorenorZorro3000** [comment]
OK, war ein versuch wert ^^

**Comment by deso85** [comment]
Ich hatte das an anderer Stelle schon in der Form angefragt, dass man optional mit ISO Codes in der Variable arbeitet. Dann könnte man {episodeNameDE} angeben. Wenn der Namen nicht existiert könnte dann auf den Default zurückgegriffen werden.

**Comment by stratuma** [comment]
![grafik](https://github.com/stratuma/Crunchyroll-Downloader-v4.0/assets/166541445/7e7ca67f-68df-49d6-8d69-82533ca93186)

Hab jetzt n selector eingebaut

**Comment by LorenorZorro3000** [comment]
Cool,, da bin ich jetzt auf die nächste Version gespannt.

Vielen Dank!

**Comment by stratuma** [comment]
Hinzugefügt in v1.2.1
