### ISSUE TITLE
Failed to get Crunchyroll Metadata

### ISSUE THREAD

**Issue by TaMaGo-TTV** [stratuma/Crunchyroll-Downloader-v4.0#17]
![image](https://github.com/stratuma/Crunchyroll-Downloader-v4.0/assets/61699515/b6d376d2-b82e-4b21-8969-d7d22b2514f5)

Ist das ein Problem oder kann man das ignorieren?

**Comment by stratuma** [comment]
Habe den bug schon behoben, release gleich 1.2.0

**Comment by TaMaGo-TTV** [comment]
> Habe den bug schon behoben, release gleich 1.2.0

Ah okay stark.

Kurze Frage zum Stream Endpoint, welches würdest du dort empfehlen?

**Comment by stratuma** [comment]
> Kurze Frage zum Stream Endpoint, welches würdest du dort empfehlen?

Macht eigentlich keinen unterschied welchen du nimmst

**Comment by TaMaGo-TTV** [comment]
> Macht eigentlich keinen unterschied welchen du nimmst

Okay alles klar, ist in Zukunft geplant Audio und Sups einzeln runterzuladen?

**Comment by stratuma** [comment]
> Okay alles klar, ist in Zukunft geplant Audio und subs einzeln runterzuladen?

Ja, werde ich höchstverscheinlich in v1.2.1 hinzufügen

**Comment by TaMaGo-TTV** [comment]
> Ja, werde ich höchstverscheinlich in v1.2.1 hinzufügen

Okay, gut zu wissen, danke auf jeden Fall für deine Mühe.

**Comment by stratuma** [comment]
Gefixt in v1.2.0
