### ISSUE TITLE
Build instructions?

### ISSUE THREAD

**Issue by Meivyn** [stratuma/Crunchyroll-Downloader-v4.0#18]
I've been trying to build this project, but unfortunately, it shows this error after running the application.

![image](https://github.com/stratuma/Crunchyroll-Downloader-v4.0/assets/793322/322f8502-155a-4db4-96fc-c87f1586cc92)

Could you please provide some build instructions? What version of Node does this require?

Thank you.

**Comment by stratuma** [comment]
# Build guide for Crunchyroll Downloader

Requires:
1. NodeJS v19 or newer
2. FFMPEG Binaries (for your os)
3. MP4Decrypt Binaries (for your os)

1. Clone the repo: `git clone https://github.com/stratuma/Crunchyroll-Downloader-v4.0.git`

2. Use PNPM to install the packages `pnpm i`

3. Go to node_modules and search for the folder jsencrypt, open the jsencrypt.js file located in bin and replace this:
```
(function webpackUniversalModuleDefinition(root, factory) {
    if(typeof exports === 'object' && typeof module === 'object')
        module.exports = factory();
    else if(typeof define === 'function' && define.amd)
        define([], factory);
    else if(typeof exports === 'object')
        exports["JSEncrypt"] = factory();
    else
        root["JSEncrypt"] = factory();
})(window, () => {

```

with this:
```
(function (root, factory) {
  if (typeof exports === 'object' && typeof module === 'object')
      module.exports = factory();
  else if (typeof define === 'function' && define.amd)
      define([], factory);
  else if (typeof exports === 'object')
      exports["JSEncrypt"] = factory();
  else
      root["JSEncrypt"] = factory();
})(typeof self !== 'undefined' ? self : this, () => {
```

4. Put the ffmpeg binaries in the ffmpeg folder and the mp4decrypt binaries in the mp4decrypt folder.

5. To run dev run `pnpm dev:electron`  when on linux or mac, for windows use `pnpm dev:electron:win`

6. To build use the command `pnpm build:electron`

Note:
To change the platform you want to build (Windows, Linux, MacOS) you have to change the const in build.js `const platform = 'WINDOWS'` on line 70

**Comment by stratuma** [comment]
I will add them to the readme asap

**Comment by stratuma** [comment]
Added
