### ISSUE TITLE
[BUG] Deactivating/Activating Season folder doesn't work

### ISSUE THREAD

**Issue by Vorffeed** [stratuma/Crunchyroll-Downloader-v4.0#20]
**Describe the bug**
The new implementation of enabling and disabling season folder creation does not work, it does not create them even if the option is checked, and if you uncheck it and return to see if the change has been made, it becomes checked again. Even though it appears checked, it does not create the folder.

**To Reproduce**

**Screenshots**
![image](https://github.com/stratuma/Crunchyroll-Downloader-v4.0/assets/10000442/3c699709-1425-43a8-9dbe-2d54855f45b8)

**Desktop (please complete the following information):**
 - OS: [windows]
 - Browser [chrome]
 - Version [v1.2.0]

**Comment by deso85** [comment]
Can confirm it, but it worked for me to uncheck and check without closing the settings menu. I guess the check is shown by default even if the option is not set and when you uncheck it there is no change but by actively activating it the setting is changes.

**Comment by stratuma** [comment]
Thx for the bugreport.
I'm going to investigate it

**Comment by stratuma** [comment]
Fixed in v1.2.1
