### ISSUE TITLE
[BUG] Metadata title not correct

### ISSUE THREAD

**Issue by deso85** [stratuma/Crunchyroll-Downloader-v4.0#25]
Hi!

I updated to 1.2.1 and now the mkv files seem to have titles which are not correct.

To check it I opened the mkv with MKVToolNix Gui.
![image](https://github.com/stratuma/Crunchyroll-Downloader-v4.0/assets/18106134/0a7432d0-2498-4cbe-ab31-f437b7db994f)

Would it be possible to delete the title?

Thanks!

**Comment by stratuma** [comment]
Hello,
Thx for the bugreport.
I already found the error and wrote a fix.

**Comment by stratuma** [comment]
Fixed in v1.2.2
