### ISSUE TITLE
[BUG] Download crashes if a single sub playlist isn't found

### ISSUE THREAD

**Issue by deso85** [stratuma/Crunchyroll-Downloader-v4.0#26]
Hi again!

It seems like the whole download doesn't start if the subtitle playlist is noch found. I don't know what it causes but it could be interesting to warn the user but give the option to download the file without subtitles.

![image](https://github.com/stratuma/Crunchyroll-Downloader-v4.0/assets/18106134/77523909-c830-42fc-a31e-02a1c06e5ac2)

Thanks

**Comment by stratuma** [comment]
It looks like its a error on crunchyrolls part.
![grafik](https://github.com/stratuma/Crunchyroll-Downloader-v4.0/assets/166541445/7aad3eaf-3e20-455c-90be-8be2cac68769)
The versions array is empty even if there are more versions, so I can't do much about it.

![grafik](https://github.com/stratuma/Crunchyroll-Downloader-v4.0/assets/166541445/77414096-99c4-4063-9b4a-ab745f37556c)
JP version

**Comment by stratuma** [comment]
Fixed in v1.2.2
