### ISSUE TITLE
[BUG] Chinese Sub/Dub selection missing

### ISSUE THREAD

**Issue by Fu2chN** [stratuma/Crunchyroll-Downloader-v4.0#27]
**Is your feature request related to a problem? Please describe.**
Hi, no chinese (zh-CN) dub can be preselected in config page.

**Describe the solution you'd like**
Add this on a config page.
![341909845-6b460124-4b42-4771-b6c9-17321a3aa97e](https://github.com/stratuma/Crunchyroll-Downloader-v4.0/assets/13276983/39623600-420b-41bd-affb-6d6051de051e)

**Comment by stratuma** [comment]
Thx for the report.
Could you send me please a url to a series that has chinese subtitles, I can't find one.

**Comment by Fu2chN** [comment]
Yes, "Dragon Raja" Chinses for Dubs, for subs i'don't know.
https://www.crunchyroll.com/fr/series/GDKHZEJN0/dragon-raja--the-blazing-dawn-

**Comment by stratuma** [comment]
Thank you, I added it. But you have to wait until I release the new version

**Comment by stratuma** [comment]
Added in v1.2.2
