### ISSUE TITLE
[BUG] Subtitle resampler doesn't resample maps

### ISSUE THREAD

**Issue by Fu2chN** [stratuma/Crunchyroll-Downloader-v4.0#28]
**Describe the bug**
Hi, the subtitle border have an error.

**Exemple title**
Chillin’ in Another World with Level 2 Super Cheat Powers - Episode 01
https://www.crunchyroll.com/fr/watch/GD9UVM9N3/a-level-2-hero-candidate

**Expected behavior**
Wrong

> [Script Info]
> Title: Français (France)
> Original Script: crd  [https://github.com/stratuma/]
> Original Translation: 
> Original Editing: 
> Original Timing: 
> Synch Point: 
> Script Updated By: 
> Update Details: 
> ScriptType: v4.00+
> Collisions: Normal
> PlayResX: 1920
> PlayResY: 1080
> Timer: 0.0000
> WrapStyle: 0
> 
> [V4+ Styles]
> Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
> Style: Default,Trebuchet MS,66,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,3,1,2,6,6,75,1
> Style: Italique,Trebuchet MS,66,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,-1,-1,0,0,100,100,0,0,1,3,1,2,6,6,75,1
> Style: TiretsDefault,Trebuchet MS,66,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,3,1,1,60,6,75,1
> Style: Titre,Georgia,66,&H00FFFFFF,&H000000FF,&H00292929,&H00000000,-1,0,0,0,100,100,0,0,1,0,0,8,30,30,150,1
> Style: Sign,Arial,54,&H00FFFFFF,&H000000FF,&H00292929,&H00000000,0,0,0,0,100,100,0,0,1,3,0,8,30,30,150,1
> 
> [Events]
> Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
> Dialogue: 0,0:00:00.02,0:00:05.48,Sign,Sign,0000,0000,0000,,{\fad(375,0)\p1\an5\bord0\pos(951,855)\1c&HF6FEF9&}m 0 0 l 220 0 l 220 40 l 0 40
> Dialogue: 1,0:00:00.02,0:00:05.48,Sign,Sign,0000,0000,0000,,{\fad(375,0)\an5\fnGeorgia\b1\bord0\1c&H032B4E&\fs54\fscy120\fscx105\pos(951,855)}PALMA,\NLA CAPITALE ROYALE

Good

> [Script Info]
> ScaledBorderAndShadow: yes
> Title: Français (France)
> Original Script: cr_fr  [http://www.crunchyroll.com/user/cr_fr]
> Original Translation: 
> Original Editing: 
> Original Timing: 
> Synch Point: 
> Script Updated By: 
> Update Details: 
> ScriptType: v4.00+
> Collisions: Normal
> PlayResX: 640
> PlayResY: 360
> Timer: 0.0000
> WrapStyle: 0
> 
> [V4+ Styles]
> Format: Name,Fontname,Fontsize,PrimaryColour,SecondaryColour,OutlineColour,BackColour,Bold,Italic,Underline,Strikeout,ScaleX,ScaleY,Spacing,Angle,BorderStyle,Outline,Shadow,Alignment,MarginL,MarginR,MarginV,Encoding
> Style: Default,Trebuchet MS,22,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,1,1,2,0002,0002,0025,1
> Style: Italique,Trebuchet MS,22,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,-1,-1,0,0,100,100,0,0,1,1,1,2,0002,0002,0025,1
> Style: TiretsDefault,Trebuchet MS,22,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,1,1,1,0020,0002,0025,1
> Style: Titre,Georgia,22,&H00FFFFFF,&H000000FF,&H00292929,&H00000000,-1,0,0,0,100,100,0,0,1,0,0,8,0010,0010,0050,1
> Style: Sign,Arial,18,&H00FFFFFF,&H000000FF,&H00292929,&H00000000,0,0,0,0,100,100,0,0,1,1,0,8,0010,0010,0050,1
> 
> [Events]
> Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
> Dialogue: 0,0:00:00.02,0:00:05.48,Sign,Sign,0000,0000,0000,,{\fad(375,0)\p1\an5\bord0\pos(317,285)\c&HF6FEF9&}m 0 0 l 220 0 l 220 40 l 0 40
> Dialogue: 1,0:00:00.02,0:00:05.48,Sign,Sign,0000,0000,0000,,{\fad(375,0)\an5\fnGeorgia\b1\bord0\c&H032B4E&\fs18\fscy120\fscx105\pos(317,285)}PALMA,\NLA CAPITALE ROYALE

**Screenshots**
Wrong
![image_wrong](https://github.com/stratuma/Crunchyroll-Downloader-v4.0/assets/13276983/ccd7b3f6-c02f-4ced-8004-462a7b5afb80)

Good
![image_good](https://github.com/stratuma/Crunchyroll-Downloader-v4.0/assets/13276983/bed1bd46-0c57-4daf-b583-e678a7dbfb3f)

**Comment by stratuma** [comment]
what did you download?

**Comment by Fu2chN** [comment]
> what did you download?

Chillin’ in Another World with Level 2 Super Cheat Powers - Episode 01
https://www.crunchyroll.com/fr/watch/GD9UVM9N3/a-level-2-hero-candidate

**Comment by stratuma** [comment]
I added some stuff to the resampler, this will fix every map problem (not even aegisub can resample that shit right)

**Comment by stratuma** [comment]
![vlcsnap-2024-06-22-22h54m24s952](https://github.com/stratuma/Crunchyroll-Downloader-v4.0/assets/166541445/e76d98f9-c658-4b35-bfa9-f5e0614686f0)

I added map support and fixed some stuff, the maps are now resampled right

**Comment by stratuma** [comment]
Fixed in v1.2.2
