### ISSUE TITLE
[QUESTION] Audio Setting

### ISSUE THREAD

**Issue by TaMaGo-TTV** [stratuma/Crunchyroll-Downloader-v4.0#30]
![image](https://github.com/stratuma/Crunchyroll-Downloader-v4.0/assets/61699515/ac7e690f-5bb3-4f00-bda9-b97956c0c769)
Was ist der unterschied von 44.10khz und 44.10khz (2)?

**Comment by stratuma** [comment]
Crunchyroll gibt 2 44.10 kHz Playlists mit.
Aber egal welche du aussuchst es ist immer das gleiche, ich hab nur beide hinzugefügt damit auch alles 100% custom einstellbar ist.

**Comment by TaMaGo-TTV** [comment]
> Crunchyroll gibt 2 44.10 kHz Playlists mit. Aber egal welche du aussuchst es ist immer das gleiche, ich hab nur beide hinzugefügt damit auch alles 100% custom einstellbar ist.

Okay sehr nice. 

Respekt wie du gerade am hustle bist, haust hier update und fix am laufenden Band raus insane.

**Comment by stratuma** [comment]
Jetzt da hama's downloader nichtmehr funktioniert muss ich ein würdigen Nachfolger coden😂

**Comment by TaMaGo-TTV** [comment]
> Jetzt da hama's downloader nichtmehr funktioniert muss ich ein würdigen Nachfolger coden😂

Wo lebste eig das du den Downloader mit der dencryption machst? Oder biste da auch bisschen gefährlich unterwegs?

**Comment by stratuma** [comment]
> Wo lebste eig das du den Downloader mit der dencryption machst? Oder biste da auch bisschen gefährlich unterwegs?

Ich lebe in Italien, wo es eigentlich auch ein wenig "gefährlich" ist. 
Solange ich aber kein cease and desist bekomme werde ich die decryption nicht rausnehmen.

**Comment by TaMaGo-TTV** [comment]
> Crunchyroll gibt 2 44.10 kHz Playlists mit.
> Aber egal welche du aussuchst es ist immer das gleiche, ich hab nur beide hinzugefügt damit auch alles 100% custom einstellbar ist.

Ahh nice one okay check

**Comment by stratuma** [comment]
Schon lustig dass das Gesetzt das umgehen von DRM verbietet aber nicht den Anbieter zwingt den User eine Kopie für den Eigenbedarf downloaden zu lassen.

**Comment by TaMaGo-TTV** [comment]
> Schon lustig dass das Gesetzt das umgehen von DRM verbietet aber nicht den Anbieter zwingt den User eine Kopie für den Eigenbedarf downloaden zu lassen.

Ehrlich ich check das auch nicht....

**Comment by stratuma** [comment]
Ich hoffe ne fette illegale Streamingseite taucht auf und reitet Crunchyroll in die schulden

**Comment by TaMaGo-TTV** [comment]
Ayo Frage zu VPN, würdest du sagen windscribe ist strong?

Hab viel gelesen das die eig ganz gut sein, nicht so wie Nord VPN XDD

**Comment by stratuma** [comment]
> Ayo Frage zu VPN, würdest du sagen windscribe ist strong?

Ne hol dir https://mullvad.net/de

**Comment by TaMaGo-TTV** [comment]
> Ich hoffe ne fette illegale Streamingseite taucht auf und reitet Crunchyroll in die schulden

yoooooo aber wird schwierig wegen Sony die haben zu viel Kohle.

**Comment by TaMaGo-TTV** [comment]
> > Ayo Frage zu VPN, würdest du sagen windscribe ist strong?
> 
> Ne hol dir https://mullvad.net/de

Das wär meine zweite Frage gewesen XD

**Comment by stratuma** [comment]
> yoooooo aber wird schwierig wegen Sony die haben zu viel Kohle.

Wenn die seite 80% des traffics von Crunchyroll stehlt kann Crunchyroll dichtmachen

**Comment by stratuma** [comment]
> Das wär meine zweite Frage gewesen XD

ProtonVPN ist eigentlich auch akzeptabel

**Comment by TaMaGo-TTV** [comment]
> Wenn die seite 80% des traffics von Crunchyroll stehlt kann Crunchyroll dichtmachen

Ja, bekomm das mal hin. Kurz Andrew Tate anrufen und fragen, ob der crunchy aufkauft Xd

Ich hab jetzt erstmal windscribe für nh Jahr bekommen fürn zwambo kann man sich nicht beschweren.

Aber dann steig ich auf Mullvad um

**Comment by stratuma** [comment]
> Ja, bekomm das mal hin. Kurz Andrew Tate anrufen und fragen, ob der crunchy aufkauft Xd

Wenn du ne handyapp, pc app und smarttv app rausbringst haste schonmal n großteil des marktes, denn wer will nicht 10€ im Monat sparen xD

> Ich hab jetzt erstmal windscribe für nh Jahr bekommen fürn zwambo kann man sich nicht beschweren.
> 
> Aber dann steig ich auf Mullvad um

Cool, hatte mir mal 2 Jahre surfshark gekauft, die kacke hab ich nie benutzt und dann vor ein paar wochen ne email bekommen dass die kacke ausläuft xD

**Comment by TaMaGo-TTV** [comment]
Nice one XDD

Auf jeden Fall dickes danke für deine Arbeit, ohne den Downloader müsste ich Streamfap oder auf Torrent zurückgreifen.

**Comment by stratuma** [comment]
> Auf jeden Fall dickes danke für deine Arbeit, ohne den Downloader müsste ich Streamfap oder auf Torrent zurückgreifen.

Kein Ding, mein Kollege hat mich dazu genötigt einen zu coden weil hamas downloader alle 2 Tage nicht funktioniert hat xD

**Comment by TaMaGo-TTV** [comment]
> > Auf jeden Fall dickes danke für deine Arbeit, ohne den Downloader müsste ich Streamfap oder auf Torrent zurückgreifen.
> 
> Kein Ding, mein Kollege hat mich dazu genötigt einen zu coden weil hamas downloader alle 2 Tage nicht funktioniert hat xD

Kuss an dein Kollegen XDD

Würde ja gerne mithelfen aber hab  Studium gedropped wird also nichts XD

**Comment by TaMaGo-TTV** [comment]
Wünsch dir auf jeden Fall nh schönen Abend aka Nacht und freu m ich auf kommende improvements usw.

**Comment by stratuma** [comment]
> Wünsch dir auf jeden Fall nh schönen Abend aka Nacht und freu m ich auf kommende improvements usw.

Jo danke dir auch noch n schönen Abend/Nacht.
