### ISSUE TITLE
Failed to get Video Playlist

### ISSUE THREAD

**Issue by hazy-kun** [stratuma/Crunchyroll-Downloader-v4.0#31]
**Describe the bug**
JWT error trying to download content

**To Reproduce**
I just tried downloading one season. Obv retried opfter new login and nothing changed

**Expected behavior**

**Screenshots**
![image](https://github.com/stratuma/Crunchyroll-Downloader-v4.0/assets/145157126/3cc0afef-59f8-4592-8139-0e676aac22ec)

**Desktop (please complete the following information):**
 - OS: Windows 11 x64
 - Version 1.2.2

**Comment by stratuma** [comment]
Try to log out and login again, or change the accesspoint to samsung tv in settings -> crunchyroll

**Comment by hazy-kun** [comment]
Thanks, solved for now
