### ISSUE TITLE
[BUG] It needs multiple tries to login (Error 406 Not Acceptable)

### ISSUE THREAD

**Issue by Raphael1512** [stratuma/Crunchyroll-Downloader-v4.0#33]
![Screenshot 2024-06-23 093753](https://github.com/stratuma/Crunchyroll-Downloader-v4.0/assets/166643560/cc391ead-f90a-4377-86a4-a40833924fae)

**Comment by Raphael1512** [comment]
Dopo alcuni tentativi ha effetuato il login, e sembra funzionare.

**Comment by stratuma** [comment]
It looks like Crunchyroll updated something again, I will investigate it.

**Comment by stratuma** [comment]
I somehow can't reproduce this error

**Comment by Raphael1512** [comment]
it must have been a coincidence... after I updated to version 1.2.2 it didn't immediately give the error, it made me download an episode and then it appeared. after a few attempts he logged in and has been working without any problems since then.

**Comment by stratuma** [comment]
Maybe a temporary outrage of crunchyroll?

**Comment by Raphael1512** [comment]
it could be, at that moment I was downloading "The Daily Life of the Immortal King" and I noticed that since the default language was not Japanese but Chinese it gave me some errors, even though it allowed me to download everything without problems. maybe it came from this... I'll attach the screenshots to be clearer.

**Comment by Raphael1512** [comment]
![Screenshot 2024-06-23 162905](https://github.com/stratuma/Crunchyroll-Downloader-v4.0/assets/166643560/d60769e1-23e3-49d7-8ff7-fa4e5a71c554)

**Comment by stratuma** [comment]
The login process has nothing to do with the download process.



> ![Screenshot 2024-06-23 162905](https://private-user-images.githubusercontent.com/166643560/342071823-d60769e1-23e3-49d7-8ff7-fa4e5a71c554.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxNTMyNjksIm5iZiI6MTcxOTE1Mjk2OSwicGF0aCI6Ii8xNjY2NDM1NjAvMzQyMDcxODIzLWQ2MDc2OWUxLTIzZTMtNDlkNy04ZmY3LWZhNGU1YTcxYzU1NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyM1QxNDI5MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMzQzZmNiMGY3ZTRjMDU1MWNlYzQxYjA5ODE5MzlmZjM5Y2YxMzI1OTM5OTgxZGRjMzU0NWQ0MjMzNGYyN2EyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XsvvKyVeGqidn07tod5NRYscO8ChgHQpioUmBzXkv4I)

It looks like crunchyroll has a mess in the api again.

**Comment by Raphael1512** [comment]
ah I understand, however I repeat that it downloads everything as per settings, even if it gives errors. about access, I don't know... but it doesn't give me any more problems, if it ever happens to me again I'll let you know. thanks anyway

**Comment by stratuma** [comment]
> ah I understand, however I repeat that it downloads everything as per settings, even if it gives errors. about access, I don't know... but it doesn't give me any more problems, if it ever happens to me again I'll let you know. thanks anyway

Perfect, just open a new issue if you encounter this error again
